### ISSUE TITLE
Stats Command 

### ISSUE THREAD

**Issue by yatishrai** [Ariz-z/Moderation-By-Pokemon-Bot#4]
Instead of manually writing `Ariz#0001` or whatever discord tag , you should actually fetch the tag from discord using id . Because of this , it will automatically show your current username and tag in the stats command. That would be very handy.

`user = bot.get_user(user_id)`

Signing off , 
YASH

**Comment by satyammpandeyy** [comment]
Yes

**Comment by Ariz-z** [comment]
Sure Thanks for telling will update it soon.

**Comment by satyammpandeyy** [comment]
Soon? Lazy boy do it right now

**Comment by Ariz-z** [comment]
Bruh I don't have only this project. I have other project too and also its not a bit issue

**Comment by satyammpandeyy** [comment]
You had wasted your time already in typing that message you could do it at that time only 💀
Thanks me later.

**Comment by satyammpandeyy** [comment]
@Ariz-z should I make an pull request? If you can't do it yourself / you're lazy doing that

**Comment by Ariz-z** [comment]
If you can then do it. No one stop you to do anything but it should be correct

**Comment by satyammpandeyy** [comment]
"but it should be correct"
I don't believe in my self idk if it would be correct jk 
I'll do after sometime I have to study right bye cya!

**Comment by Ariz-z** [comment]
Then go study don't waste time here dude :)

**Comment by Ariz-z** [comment]
> Also bot.get_user(user) needs Guild Member Intent. + Sometimes it shows None. For Eg: 
![image](https://user-images.githubusercontent.com/43195493/146048518-c7c60ae9-4fe6-46b1-924a-d574aa63f974.png)

**Comment by Ariz-z** [comment]
Done Fixed. But you need to enable Guild Member Intent for that. 

> Instead of manually writing `Ariz#0001` or whatever discord tag , you should actually fetch the tag from discord using id . Because of this , it will automatically show your current username and tag in the stats command. That would be very handy.
> 
> `user = bot.get_user(user_id)`
> 
> Signing off , YASH

**Comment by Ariz-z** [comment]
Solved
